### ISSUE TITLE
How to display the emoji?

### ISSUE THREAD

**Issue by BadElement** [jeffreytse/jekyll-theme-yat#42]
I like your theme very much, but I can’t solve this problem independently.

This is the demo from your Repository:
![图片](https://user-images.githubusercontent.com/52056834/119300704-ca966380-bc93-11eb-9844-2bd4ebcd7be7.png)

Here is mine:
![图片](https://user-images.githubusercontent.com/52056834/119300849-04676a00-bc94-11eb-89a5-9f1dc71cca5b.png)

**Comment by jeffreytse** [comment]
Hi @BadElement 

Firstly, thanks for loving this theme, and your issue is common. I would love to tell you that the emoji feature is supported by the [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship) plugin, this plugin is a third-party plugin, so that it can not be supported by the Github Page directly, as [the description](https://github.com/jeffreytse/jekyll-spaceship#additions-for-unlimited-github-pages) in the document.

To solve this issue, you should use a Github Action, in this theme, you can easily find [it](https://github.com/jeffreytse/jekyll-theme-yat/blob/master/.github/workflows/build-jekyll.yml), you can quickly deploy it by following the instructions of the [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) document.

Also, welcome to star these projects I made for the further updates in the future. : )

Thanks and regards

**Comment by BadElement** [comment]
那真是太棒了！
可是要如何避免填在build-jekyll.yml的token被git上传呢？
我看了你的博客的仓库，你没有在.gitignore里忽视build-jekyll.yml，但是却没有这个文件
如何做到的？？

====

that's awsome！
but,how to escape the token that is in build-jekyll.yml from being uploaded by git
i saw your blog repositorie，you didn't ignore the file in .gitignore,but it no such file
how done that?

**Comment by jeffreytse** [comment]
@BadElement 

You should study from the theme repository (i.e. [jekyll-theme-yat](https://github.com/jeffreytse/jekyll-theme-yat) and `.github/workflows/build-jekyll.yml`), and follow the instructions from [jekyll-deploy-action](https://github.com/jeffreytse/jekyll-deploy-action) step by step, the token is as a secrect and saving in the repository, others can not get it.

Thanks and regards

**Comment by BadElement** [comment]
谢谢你的帮助！！！
我根据文档做好了设置
github action运行也没问题
![图片](https://user-images.githubusercontent.com/52056834/119338947-32b06e00-bcc3-11eb-9752-253adf25370b.png)

**但还是....错误**
https://badelement.github.io/

我根本找不出这个错误的原因
能帮助我解决这个问题吗？
不胜感激....

**Comment by jeffreytse** [comment]
Hi @BadElement 

I think it's your wrong configuration caused this issue, that is some resources not be loaded correctly.


Please set your `baseurl` inside `_config.yml` to a correct value, as below:

```yml
baseurl: ""
```

And check the option inside `.github/workflows/build-jekyll.yml` 

```yml
jekyll_baseurl: ''
```

Thanks and regards

**Comment by BadElement** [comment]
显示正常了........
但是emoji错误仍然存在
1.
![图片](https://user-images.githubusercontent.com/52056834/119345499-8b840480-bccb-11eb-8f9a-69e8bdfa61bf.png)
2.
![图片](https://user-images.githubusercontent.com/52056834/119345533-95a60300-bccb-11eb-96bd-065ff199ddf5.png)


但这个却是正常的:
![图片](https://user-images.githubusercontent.com/52056834/119345648-be2dfd00-bccb-11eb-804c-4a82f00be8ac.png)

**Comment by BadElement** [comment]
还有你可以在文字下面**增加**英文，这样就不用**替换**，保留中文方便中文读者啊23333
you can **add** English below the text, so you don't need to **replace**, and keep the Chinese for Chinese readers 23333

**Comment by jeffreytse** [comment]
Hi, @BadElement 

I think you did not add the [jekyll-spaceship](https://github.com/jeffreytse/jekyll-spaceship) plugin, please add it to your Gemfile as below

```yml
gem "jekyll-spaceship", group: :jekyll_plugins
```  

Thanks and regards

**Comment by BadElement** [comment]
EMOJI显示正常了！
谢谢你的帮助！
Emoji display is normal!
thank you for your help!
![图片](https://user-images.githubusercontent.com/52056834/119414777-ce24fb80-bd22-11eb-8976-e01fbe6210e9.png)

**Comment by CypherpunkSamurai** [comment]
> 
> 
> 还有你可以在文字下面**增加**英文，这样就不用**替换**，保留中文方便中文读者啊23333
> you can **add** English below the text, so you don't need to **replace**, and keep the Chinese for Chinese readers LOL

Usually github repo's don't have bilingual readme. If you want to contribute for a chinese readme feel free.
